APPLICATION=screen_test

BOARD=esp32-heltec-lora32-v2

RIOTBASE = /home/nicods/Scrivania/SmartMuseum/Boards/RIOT

FEATURES_REQUIRED += periph_gpio periph_i2c
USEPKG += u8g2

USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
